### ISSUE TITLE
"sudo cp target/release/help-ukraine /usr/bin/help-ukraine" sur windows

### ISSUE THREAD

**Issue by jcbevc** [SkwalExe/help-ukraine#1]
comment je fais la partie "sudo cp target/release/help-ukraine /usr/bin/help-ukraine" sur windows?

**Comment by SkwalExe** [comment]
Cette commande a pour effet de déplacer l'executable binaire  dans un dossier de path pour qu'il soit reconnu en tant que commande.

Mais ce n'est pas obligatoire, pour l'executer, on peut le trouver ici : (apres le build) 

[dossier help-ukraine apres le clonage] -> target -> release -> help-ukraine.exe

vous pouvez déplacer ce fichier seul ou vous le voulez pour le l'executer plus facilement

**Comment by SkwalExe** [comment]
Ces informations ont été ajoutées au readme
